apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: lec-12

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf

generatorOptions:
  disableNameSuffixHash: true

namePrefix: lec-12-

resources:
- nginx-deployment.yml
- ../wiremock/mappings